#Tipe Database
quarkus.datasource.db-kind=postgresql

#URL Database (Port default PostgreSQL biasanya 5432)
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres

#Username & Password PostgreSQL laptopmu
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

#Otomatis buatkan tabel di PostgreSQL
quarkus.hibernate-orm.database.generation=drop-and-create

# Enable CORS Serbaguna (Dev Mode)
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# JWT Config
mp.jwt.verify.issuer=https://qr-studio.com